/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { AttributeModifier } from './component/common';
import { ImageSpanAttribute } from './component/imageSpan';

/**
 * @file
 * @kit ArkUI
 * @arkts 1.2
 */

/**
 * Defines TextInput Modifier
 *
 * @implements ImageSpanAttribute, AttributeModifier<ImageSpanAttribute>
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @since 20
*/
export declare class ImageSpanModifier implements ImageSpanAttribute, AttributeModifier<ImageSpanAttribute> {}
