'use static'
/*
 * Copyright (C) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * @file
 * @kit ArkUI
 * @arkts 1.2
 */

import { Builder } from './builder';
import { Theme } from '@ohos.arkui.theme';
import { UIContext } from '@ohos.arkui.UIContext';
import { Optional, NavDestinationInfo, NavigationInfo, RouterPageInfo } from './common';

/**
 * Defining interface of LifeCycle for custom component and custom dialog
 *
 * @typedef LifeCycle
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @since 20
 */
export declare interface LifeCycle {
    /**
     * aboutToAppear Method.
     *
     * The aboutToAppear function is executed after a new instance of the custom component is created,
     * before its build() function is executed.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @since 20
     */
    default aboutToAppear(): void;

    /**
     * aboutToDisappear Method.
     *
     * The aboutToDisappear function executes before a custom component is destroyed.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @since 20
     */
    default aboutToDisappear(): void;

    /**
     * The callback method after the custom component is built.
     *
     * Triggered when the custom component has been built.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @since 20
     */
    default onDidBuild(): void;

    /**
     * Customize the build process of the custom component.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @since 20
     */
    @Builder
    build(): void
}

/**
 * Definition of extendable component, which is base class of custom component and custom dialog.
 *
 * @implements LifeCycle
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @since 20
 */
export declare abstract class ExtendableComponent implements LifeCycle {
    /**
     * onWillApplyTheme function is a custom hook to get active theme object from the context.
     *
     * @param { Theme } theme - Custom theme init params.
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @since 20
     */
    onWillApplyTheme(theme: Theme): void;

    /**
     * Get current UIContext.
     *
     * @returns { UIContext } The UIContext that the custom component belongs to.
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @since 20
     */
    getUIContext(): UIContext

    /**
     * Get uniqueId of the custom component.
     *
     * @returns { int } - The uniqueId of the custom component.
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @since 20
     */
    getUniqueId(): int
    
    /**
    * Queries the navigation destination information.
    *
    * @returns { NavDestinationInfo | undefined } The navigation destination information, or undefined if it is not available.
    * @syscap SystemCapability.ArkUI.ArkUI.Full
    * @since 20
    */
    queryNavDestinationInfo(): NavDestinationInfo | undefined;

    /**
    * Queries the navigation destination information.
    *
    * @param { Optional<boolean> } isInner
    * @returns { NavDestinationInfo | undefined } The navigation destination information, or undefined if it is not available.
    * @syscap SystemCapability.ArkUI.ArkUI.Full
    * @since 20
    */
    queryNavDestinationInfo(isInner: Optional<boolean>): NavDestinationInfo | undefined;

    /**
    * Query the navigation information of the current custom component.
    *
    * @returns { NavigationInfo | undefined } The navigation information, or undefined if it is not available
    * @syscap SystemCapability.ArkUI.ArkUI.Full
    * @since 20
    */
    queryNavigationInfo(): NavigationInfo | undefined;

    /**
    * Query the router page information of the current custom component.
    *
    * @returns { RouterPageInfo | undefined } The router page information, or undefined if it is not available.
    * @syscap SystemCapability.ArkUI.ArkUI.Full
    * @since 20
    */
    queryRouterPageInfo(): RouterPageInfo | undefined;
}
