/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { AsyncCallback } from '../../basic'

/**
* Provides methods for accessing a database result set generated by querying the database.
*
* @devices phone, tablet, tv, wearable, car
* @Syscap SystemCapability.Data.DATA_APPDATAMGR
* @version 7
*/

interface ResultSet {
    /**
     * Obtains the names of all columns in a result set.
     *
     * The column names are returned as a string array, in which the strings are in the same order
     * as the columns in the result set.
     *
     * @since 7
     */
    columnNames: Array<string>;

    /**
     * Obtains the number of columns in the result set.
     *
     * The returned number is equal to the length of the string array returned by the
     * columnCount method.
     *
     * @since 7
     */
    columnCount: number;

    /**
     * Obtains the number of rows in the result set.
     *
     * @since 7
     */
    rowCount: number;

    /**
     * Obtains the current index of the result set.
     *
     * The result set index starts from 0.
     *
     * @since 7
     */
    rowIndex: number;

    /**
     * Checks whether the result set is positioned at the first row.
     *
     * @since 7
     */
    isAtFirstRow: boolean;

    /**
     * Checks whether the result set is positioned at the last row.
     *
     * @since 7
     */
    isAtLastRow: boolean;

    /**
     * Checks whether the result set is positioned after the last row.
     *
     * @since 7
     */
    isEnded: boolean;

    /**
     * Returns whether the cursor is pointing to the position before the first
     * row.
     *
     * @since 7
     */
    isStarted: boolean;

    /**
     * Checks whether the current result set is closed.
     *
     * If the result set is closed by calling the close method, true will be returned.
     *
     * @since 7
     */
    isClosed: boolean;

    /**
     * Obtains the column index based on the specified column name.
     *
     * The column name is passed as an input parameter.
     *
     * @param columnName Indicates the name of the specified column in the result set.
     * @return Returns the index of the specified column.
     * @since 7
     */
    getColumnIndex(columnName: string): number;

    /**
     * Obtains the column name based on the specified column index.
     *
     * The column index is passed as an input parameter.
     *
     * @param columnIndex Indicates the index of the specified column in the result set.
     * @return Returns the name of the specified column.
     * @since 7
     */
    getColumnName(columnIndex: number): string;

    /**
     * Go to the specified row of the result set forwards or backwards by an offset relative to its current position.
     * A positive offset indicates moving backwards, and a negative offset indicates moving forwards.
     *
     * @param offset Indicates the offset relative to the current position.
     * @return Returns true if the result set is moved successfully and does not go beyond the range;
     * returns false otherwise.
     * @since 7
     */
    goTo(offset: number): boolean;

    /**
     * Go to the specified row of the result set.
     *
     * @param rowIndex Indicates the index of the specified row, which starts from 0.
     * @return Returns true if the result set is moved successfully; returns false otherwise.
     * @since 7
     */
    goToRow(position: number): boolean;

    /**
     * Go to the first row of the result set.
     *
     * @return Returns true if the result set is moved successfully;
     * returns false otherwise, for example, if the result set is empty.
     * @since 7
     */
    goToFirstRow(): boolean;

    /**
     * Go to the last row of the result set.
     *
     * @return Returns true if the result set is moved successfully;
     * returns false otherwise, for example, if the result set is empty.
     * @since 7
     */
    goToLastRow(): boolean;

    /**
     * Go to the next row of the result set.
     *
     * @return Returns true if the result set is moved successfully;
     * returns false otherwise, for example, if the result set is already in the last row.
     * @since 7
     */
    goToNextRow(): boolean;

    /**
     * Go to the previous row of the result set.
     *
     * @return Returns true if the result set is moved successfully;
     * returns false otherwise, for example, if the result set is already in the first row.
     * @since 7
     */
    goToPreviousRow(): boolean;

    /**
     * Obtains the value of the specified column in the current row as a byte array.
     *
     * The implementation class determines whether to throw an exception if the value of the specified column
     * in the current row is null or the specified column is not of the Blob type.
     *
     * @param columnIndex Indicates the specified column index, which starts from 0.
     * @return Returns the value of the specified column as a byte array.
     * @since 7
     */
    getBlob(columnIndex: number): Uint8Array;

    /**
     * Obtains the value of the specified column in the current row as string.
     *
     * The implementation class determines whether to throw an exception if the value of the specified column
     * in the current row is null or the specified column is not of the string type.
     *
     * @param columnIndex Indicates the specified column index, which starts from 0.
     * @return Returns the value of the specified column as a string.
     * @since 7
     */
    getString(columnIndex: number): string;

    /**
     * Obtains the value of the specified column in the current row as long.
     *
     * The implementation class determines whether to throw an exception if the value of the specified column
     * in the current row is null, the specified column is not of the integer type
     *
     * @param columnIndex Indicates the specified column index, which starts from 0.
     * @return Returns the value of the specified column as a long.
     * @since 7
     */
    getLong(columnIndex: number): number;

    /**
     * Obtains the value of the specified column in the current row as double.
     *
     * The implementation class determines whether to throw an exception if the value of the specified column
     * in the current row is null, the specified column is not of the double type
     *
     * @param columnIndex Indicates the specified column index, which starts from 0.
     * @return Returns the value of the specified column as a double.
     * @since 7
     */
    getDouble(columnIndex: number): number;

    /**
     * Checks whether the value of the specified column in the current row is null.
     *
     * @param columnIndex Indicates the specified column index, which starts from 0.
     * @return Returns true if the value of the specified column in the current row is null;
     * returns false otherwise.
     * @since 7
     */
    isColumnNull(columnIndex: number): boolean;

    /**
     * Closes the result set.
     *
     * Calling this method on the result set will release all of its resources and makes it ineffective.
     *
     * @return Returns true if the result set is closed; returns false otherwise.
     * @since 7
     */
    close(): void;
}