/*
 * Copyright (c) 2021-2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License"),
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file CliToolEvent
 * @kit AbilityKit
 */

/**
 * Describes an event generated by a CLI tool or command during execution.
 *
 * @syscap SystemCapability.Ability.AgentRuntime.Core
 * @systemapi
 * @stagemodelonly
 * @since 26.0.0 dynamiconly
 */
export interface CliToolEvent {
  /**
   * Indicates the type of this tool event.
   *
   * @syscap SystemCapability.Ability.AgentRuntime.Core
   * @systemapi
   * @stagemodelonly
   * @since 26.0.0 dynamiconly
   */
  toolEventType: ToolEventType;

  /**
   * Indicates the data payload of this tool event.
   *
   * @syscap SystemCapability.Ability.AgentRuntime.Core
   * @systemapi
   * @stagemodelonly
   * @since 26.0.0 dynamiconly
   */
  data: string;
}

/**
 * Enumerates the event types that a CLI tool or command process can produce during execution.
 *
 * @syscap SystemCapability.Ability.AgentRuntime.Core
 * @systemapi
 * @stagemodelonly
 * @since 26.0.0 dynamiconly
 */
export enum ToolEventType {
  /**
   * Standard output event. The {@link CliToolEvent.data} field contains the
   * text written by the tool to its standard output (stdout) stream.
   *
   * @syscap SystemCapability.Ability.AgentRuntime.Core
   * @systemapi
   * @stagemodelonly
   * @since 26.0.0 dynamiconly
   */
  STDOUT = 'stdout',

  /**
   * Standard error event. The {@link CliToolEvent.data} field contains the
   * text written by the tool to its standard error (stderr) stream. Note
   * that some tools write diagnostic or progress information to stderr even
   * when execution is proceeding normally.
   *
   * @syscap SystemCapability.Ability.AgentRuntime.Core
   * @systemapi
   * @stagemodelonly
   * @since 26.0.0 dynamiconly
   */
  STDERR = 'stderr',

  /**
   * Exit event. The tool process has exited. The {@link CliToolEvent.data}
   * field contains the exit code as a string.
   *
   * @syscap SystemCapability.Ability.AgentRuntime.Core
   * @systemapi
   * @stagemodelonly
   * @since 26.0.0 dynamiconly
   */
  EXIT = 'exit',

  /**
   * Error event. The tool process encountered an error that prevented normal
   * execution. The {@link CliToolEvent.data} field contains a descriptive
   * error message.
   *
   * @syscap SystemCapability.Ability.AgentRuntime.Core
   * @systemapi
   * @stagemodelonly
   * @since 26.0.0 dynamiconly
   */
  ERROR = 'error'
}
