/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file
 * @kit ArkUI
 */

/**
 * Defines the two-dimensional vector, which contains the x and y coordinates and indicates the position relationship.
 *
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @systemapi
 * @stagemodelonly
 * @since 26.0.0 dynamic
 */
declare type Vector2 = import('../api/arkui/Graphics').Vector2;

/**
 * Defines the four-dimensional vector, which contains x, y, z, and w coordinates that indicate the barrel distortion 
 * degree.
 *
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @systemapi
 * @stagemodelonly
 * @since 26.0.0 dynamic
 */
declare type Vector4 = import('../api/arkui/Graphics').Vector4;

/**
 * Defines the spatial distortion parameters.
 * 
 * > **NOTE**
 * >
 * > - The coordinates of the four corners of the component can be set as follows: top-left corner: { x:0, y:0 }, top-right 
 * > corner: { x:1, y:0 }, bottom-left corner: { x:0, y:1 }, bottom-right corner: { x:1, y:1 }.
 * >
 * > - For example, if the **bottomLeft** attribute is set to **{ x:0.5, y:0.5 }**, the bottom-left corner is deformed to the 
 * > position of the component center, and the corresponding distortion effect is generated.
 * >
 * > - When setting the coordinates of the four corners, ensure they follow spatial logic. For example, if **topLeft** 
 * > is **{ x:0, y:0.7 }** and **bottomLeft** is **{ x:0, y:0.2 }**, the top-left corner is lower than the bottom-left corner, which
 * > violates the spatial logic and may cause rendering exceptions.
 *
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @systemapi
 * @stagemodelonly
 * @since 26.0.0 dynamic
 */
declare interface DistortionParam {
  /**
   * Coordinates of the top-left corner.
   * 
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @systemapi
   * @stagemodelonly
   * @since 26.0.0 dynamic
   */
  topLeft: Vector2;
  /**
   * Coordinates of the top-right corner.
   * 
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @systemapi
   * @stagemodelonly
   * @since 26.0.0 dynamic
   */
  topRight: Vector2;
  /**
   * Coordinates of the bottom-left corner.
   * 
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @systemapi
   * @stagemodelonly
   * @since 26.0.0 dynamic
   */
  bottomLeft: Vector2;
  /**
   * Coordinates of the bottom-right corner.
   * 
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @systemapi
   * @stagemodelonly
   * @since 26.0.0 dynamic
   */
  bottomRight: Vector2;
  /**
   * Barrel distortion degree of the four edges.
   * 
   * The four values in **Vector4** are as follows: **x** indicates the left edge, **y** indicates the right edge, **z**
   * indicates the top edge, and **w** indicates the bottom edge.
   * 
   * A positive value indicates outward distortion, and a negative value indicates inward distortion. When the absolute 
   * value of the distortion parameter reaches 1, the distortion degree is extreme.
   * 
   * Recommended value range for x, y, z, and w: **[-1, 1]**
   *
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @systemapi
   * @stagemodelonly
   * @since 26.0.0 dynamic
   */
  barrelDistortion: Vector4;
}

/**
 * Defines the DistortionComponent constructor options.
 *
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @systemapi
 * @stagemodelonly
 * @since 26.0.0 dynamic
 */
declare interface DistortionComponentOptions {
  /**
   * Spatial distortion parameters. The spatial distortion effect is generated by specifying the position relationship 
   * of four corners and the barrel distortion degree of four edges.
   *
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @systemapi
   * @stagemodelonly
   * @since 26.0.0 dynamic
   */
  distortion?: DistortionParam;
}

/**
 * Create DistortionComponent.
 *
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @systemapi
 * @stagemodelonly
 * @since 26.0.0 dynamic
 */
interface DistortionComponentInterface {
  /**
   * Creates a DistortionComponent with content.
   *
   * @param { DistortionComponentOptions } [options] - DistortionComponent Options.
   * @returns { DistortionComponentAttribute }
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @systemapi
   * @stagemodelonly
   * @since 26.0.0 dynamic
   */
  (options?: DistortionComponentOptions): DistortionComponentAttribute;
}

/**
 * Defines the DistortionComponent attribute functions
 *
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @systemapi
 * @stagemodelonly
 * @since 26.0.0 dynamic
 */
declare class DistortionComponentAttribute extends CommonMethod<DistortionComponentAttribute> {}

/**
 * Defines DistortionComponent.
 *
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @systemapi
 * @stagemodelonly
 * @since 26.0.0 dynamic
 */
declare const DistortionComponent: DistortionComponentInterface;
