/*
 * Copyright (C) 2024-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
/**
 * @file State management API file
 * @kit ArkUI
 */
 
import contextConstant from '@ohos.app.ability.contextConstant';

/**
 * Function that returns default creator.
 *
 * @typedef { function } StorageDefaultCreator<T>
 * @returns { T } default creator
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 12 dynamic
 */
export declare type StorageDefaultCreator<T> = () => T;

/**
 * Define class constructor with arbitrary parameters.
 * @interface TypeConstructorWithArgs<T>
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 12 dynamic
 */
export interface TypeConstructorWithArgs<T> {
  /**
   * @param { any } args the arguments of the constructor.
   * @returns { T } return class instance.
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 12 dynamic
   */
  new(...args: any): T;
}

/**
 * Define  ConnectOptions class.
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @atomicservice
 * @since 18 dynamic
 */
export class ConnectOptions<T extends object> {
  /**
   * @type { TypeConstructorWithArgs<T> } type class type of the stored value.
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @atomicservice
   * @since 18 dynamic
   */
  type: TypeConstructorWithArgs<T>;

  /**
   * Defines alias name of the key, or the function generating the default value.
   * @type { ?string } 
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @atomicservice
   * @since 18 dynamic
  */
  key?: string;

  /**
   * Define the function generating the default value.
   * @type { ?StorageDefaultCreator<T>} 
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @atomicservice
   * @since 18 dynamic
  */
  defaultCreator?: StorageDefaultCreator<T>;

  /**
   * Define encrypted partition for data storage.
   * if not passed in, the defaule value is El2
   * 
   * @type { ?contextConstant.AreaMode} 
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @atomicservice
   * @since 18 dynamic
  */
  areaMode?: contextConstant.AreaMode;
}

/**
 * AppStorageV2 is for UI state of app-wide access, has same life cycle as the app,
 * and saves database content only in memory.
 *
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 12 dynamic
 */
export declare class AppStorageV2 {
  /**
   * If used by persistenceV2, module-level storage path, different modules will have their own storage paths.
   * If the value for the given key is already available, return the value.
   * If not, add the key with value generated by calling defaultFunc and return it to caller.
   *
   * @param { TypeConstructorWithArgs<T> } type class type of the stored value.
   * @param { string | StorageDefaultCreator<T> } [keyOrDefaultCreator] alias name of the key, or the function generating the default value.
   * @param { StorageDefaultCreator<T> } [defaultCreator] the function generating the default value
   * @returns { T | undefined } the value of the existed key or the default value
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 12 dynamic
   */
  static connect<T extends object>(
    type: TypeConstructorWithArgs<T>,
    keyOrDefaultCreator?: string | StorageDefaultCreator<T>,
    defaultCreator?: StorageDefaultCreator<T>
  ): T | undefined;

  /**
   * Removes data with the given key or given class type.
   *
   * @param { string | TypeConstructorWithArgs<T> } keyOrType key or class type removing
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 12 dynamic
   */
  static remove<T>(keyOrType: string | TypeConstructorWithArgs<T>): void;

  /**
   * Return the array of all keys.
   *
   * @returns { Array<string> } the array of all keys
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 12 dynamic
   */
  static keys(): Array<string>;
}
 
/**
 * Function that returns reason type when error.
 *
 * @typedef { function } PersistenceErrorCallback
 * @param { string } key persisted key when error
 * @param { 'quota' | 'serialization' | 'unknown' } reason reason type when error
 * @param { string } message more message when error
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 12 dynamic
 */
export declare type PersistenceErrorCallback = (key: string, reason: 'quota' | 'serialization' | 'unknown', message: string) => void;
 
/**
 * PersistenceV2 is for UI state of app-wide access, available on app re-start,
 * and saves database content in disk.
 *
 * @extends AppStorageV2
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 12 dynamic
 */
export declare class PersistenceV2 extends AppStorageV2 {
  /**
   * Application-level storage path, sharing a storage path for all modules under the application.
   * If the value for the given key is already available, return the value.
   * If not, add the key with value generated by calling defaultFunc and return it to caller.
   *
   * @param { ConnectOptions<T> } type Application level storage parameters.                                     
   * @returns { T | undefined } the value of the existed key or the default value
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @atomicservice
   * @since 18 dynamic
   */
  static globalConnect<T extends object>(
    type: ConnectOptions<T>
  ): T | undefined;

  /**
   * Used to manually persist data changes to disks.
   *
   * @param { string | TypeConstructorWithArgs<T> } keyOrType key or class type need to persist.
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 12 dynamic
   */
  static save<T>(keyOrType: string | TypeConstructorWithArgs<T>): void;

  /**
   * Be called when persisting has encountered an error.
   *
   * @param { PersistenceErrorCallback | undefined } callback called when error
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 12 dynamic
   */
  static notifyOnError(callback: PersistenceErrorCallback | undefined): void;
}
 
/**
 * Define TypeConstructor type.
 *
 * @interface TypeConstructor<T>
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 12 dynamic
 */
export interface TypeConstructor<T> {
  /**
   * @returns { T }
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 12 dynamic
   */
  new(): T;
}
 
/**
 * Function that returns PropertyDecorator.
 *
 * @typedef { function } TypeDecorator
 * @param { TypeConstructor<T> } type type info
 * @returns { PropertyDecorator } Type decorator
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 12 dynamic
 */
export declare type TypeDecorator = <T>(type: TypeConstructor<T>) => PropertyDecorator;
 
/**
 * Define Type PropertyDecorator, adds type information to an object.
 *
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 12 dynamic
 */
export declare const Type: TypeDecorator;

/**
 * UIUtils is a state management tool class for operating the observed data.
 *
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 12 dynamic
 */
export declare class UIUtils {
  /**
   * Get raw object from the Object wrapped with an ObservedObject.
   * If input parameter is a regular Object without ObservedObject, return Object itself.
   *
   * @param { T } source input source Object data.
   * @returns { T } raw object from the Object wrapped with an ObservedObject.
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 12 dynamic
   */
  static getTarget<T extends object>(source: T): T;

   /**
   * Make non-observed data into V2 observed data.
   * Support non-observed class, JSON.parse Object and Sendable class.
   *
   * @param { T } source input source object data.
   * @returns { T } V2 proxy object from the source object data.
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 12 dynamic
   */
   static makeObserved<T extends object>(source: T): T;

  /**
   * Make non-observed data into V1 observed data.
   * Support JS object, interface, class (non-@Observed, non-ObservedV2).
   *
   * @param { T } source input source object data.
   * @returns { T } V1 proxy object from the source object data.
   * @static
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 19 dynamic
   */
   static makeV1Observed<T extends object>(source: T): T;

  /**
   * Enables V2 compatibility on given viewmodel object or nested viewmodels, which are V1 observed object already.
   *
   * @param {T} source - The object to be made V2-compatible.
   * @returns {T} The processed object with V2 compatibility enabled.
   * @static
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 19 dynamic
   */
   static enableV2Compatibility<T extends object>(source: T): T;

  /**
   * Dynamically add monitor for state variable change.
   *
   * @param { object } target class instance or custom component instance.
   * @param { string | string[] } path  monitored change for state variable.
   * @param { MonitorCallback } monitorCallback the function that triggers the callback when state variable change.
   * @param { MonitorOptions} [options] the monitor configuration parameter.
   * @throws { BusinessError } 130000 - The target is not a custom component instance or V2 class instance.
   * @throws { BusinessError } 130001 - The path is invalid.
   * @throws { BusinessError } 130002 - monitorCallback is not a function or an anonymous function.
   * @static
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 20 dynamic
   */
  static addMonitor(target: object, path: string | string[], monitorCallback: MonitorCallback, options?: MonitorOptions): void;

  /**
   * Dynamically clear monitor callback for state variable change.
   *
   * @param { object } target class instance or custom component instance.
   * @param { string | string[] } path  monitored change for state variable.
   * @param { MonitorCallback } [monitorCallback] the function that triggers the callback when state variable change.
   * @throws { BusinessError } 130000 - The target is not a custom component instance or V2 class instance.
   * @throws { BusinessError } 130001 - The path is invalid.
   * @throws { BusinessError } 130002 - monitorCallback is not a function or an anonymous function.
   * @static
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 20 dynamic
   */
  static clearMonitor(target: object, path: string | string[], monitorCallback?: MonitorCallback) : void;

   /**
   * Creates read-only data binding.
   * Example. UIUtils.makeBinding<number>(()=>this.num);
   *
   * Supports simple getters for read-only data.
   * Intended for primitive value parameters when calling a @Builder function where arguments are of type Binding.
   *
   * @param { GetterCallback<T> } getter - A value or a function that returns the current value of type T.
   * @returns { Binding<T> } read-only data binding value
   * @static
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 20 dynamic
   */
  static makeBinding<T>(getter: GetterCallback<T>): Binding<T>;

  /**
   * Creates a mutable data binding.
   *
   * Two functions to implement function overloading.
   *
   * Example. UIUtils.makeBinding<number>(()=>this.num, val => this.num = val);
   *
   * Supports getter-setter pairs for mutable data.
   * Intended for primitive value parameters when calling a @Builder
   * function where arguments are of type MutableBinding.
   *
   * @param { GetterCallback<T> } getter - A value or a function that returns the current value of type T.
   * @param { SetterCallback<T> } setter - A function to set a new value of type T. 
   * If provided, a MutableBinding is created.
   * @returns { MutableBinding<T> } mutable data binding value
   * @static
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 20 dynamic
   */
  static makeBinding<T>(getter: GetterCallback<T>, setter: SetterCallback<T>): MutableBinding<T>;

  /**
   * Used to refresh the specified state variable synchronously, include update Computed, execute
   * Monitor function and rerender UINodes.
   * Calling applySync while executing task of another applySync executes the given task normally.
   *
   * @param { TaskCallback } task callback function to change state variable synchronously
   * @returns { T } the return value of the callback function
   * @throws { BusinessError } 140001 - The function is not allowed to be called in @Computed
   * @static
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 22 dynamic
   */
  static applySync<T>(task: TaskCallback) : T;
  /**
   * Used to refresh the all state variable synchronously, include update Computed, execute
   * Monitor function and rerender UINodes.
   * Calling flushUpdates() while exec applySync lambda has no effect.
   *
   * @throws { BusinessError } 140001 - The function is not allowed to be called in @Computed
   * @throws { BusinessError } 140002 - The function is not allowed to be called in @Monitor
   * @static
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 22 dynamic
   */
  static flushUpdates(): void;

  /**
   * Used to update all UINode currently synchronously.
   * Calling flushUIUpdates() while exec applySync lambda has no effect.
   *
   * @throws { BusinessError } 140001 - The function is not allowed to be called in @Computed
   * @throws { BusinessError } 140002 - The function is not allowed to be called in @Monitor
   * @static
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 22 dynamic
   */
  static flushUIUpdates(): void;

  /**
   * Determine whether the data object is observable and return the observation result.
   *
   * @param { T } source - input source object data.
   * @returns { ObservedResult } return result of whether a class is observable.
   * @static
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @stagemodelonly
   * @crossplatform
   * @atomicservice
   * @since 23 dynamic
   */
  static canBeObserved<T extends object>(source: T): ObservedResult;

  /**
   * The getLifecycle function gets the lifecycle instance of the class CustomComponent.
   *
   * @param { T } customComponent - custom component instance
   * @returns { CustomComponentLifecycle } The lifecycle that the custom component belongs to.
   * @static
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @stagemodelonly
   * @crossplatform
   * @atomicservice
   * @since 23 dynamic
   */
  static getLifecycle<T extends BaseCustomComponent>(customComponent: T): CustomComponentLifecycle;
}

/**
 * Defining the task callback.
 *
 * @typedef { function } TaskCallback
 * @returns { T }
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 22 dynamic
 */
declare type TaskCallback = () => T;

/**
 * Function that returns monitor instance value when state variable is changed.
 *
 * @typedef { function } MonitorCallback
 * @param { IMonitor} monitorValue monitor instance value when state variable is changed.
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 20 dynamic
 */
export declare type MonitorCallback = (monitorValue: IMonitor) => void;

/**
 * Define Monitor options.
 *
 * @interface MonitorOptions
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 20 dynamic
 */
export interface MonitorOptions {
  /**
   * Used to determine whether the state variable change is
   * triggered synchronously or asynchronously. The default value is false.
   *
   * @type { ?boolean } isSynchronous parameter
   * @default false
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 20 dynamic
   */
  isSynchronous?: boolean;
}

/**
 * Getter callback type. It is used to get value.
 *
 * @typedef { function } GetterCallback
 * @returns { T }
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 20 dynamic
 */
export declare type GetterCallback<T> = () => T;

/**
 * Setter callback type. It is used to assign a new value.
 *
 * @typedef { function } SetterCallback
 * @param { T } newValue - update the value with newValue.
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 20 dynamic
 */
export declare type SetterCallback<T> = (newValue: T) => void;

/**
 * Represents a read-only data binding.
 * Use with @Builder argument list for primitive types. Use makeBinding to pass values when calling the function.
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 20 dynamic
 */
export declare class Binding<T> {
  /**
   * Get function that can acquire the value.
   * @returns T
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 20 dynamic
   */
  get value(): T;
}

/**
 * Represents a mutable data binding allowing both read and write operations.
 * Use with @Builder argument list for primitive types. Use makeBinding to pass values when calling the function.
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @crossplatform
 * @atomicservice
 * @since 20 dynamic
 */
export declare class MutableBinding<T> {
  /**
   * Get function that can acquire the value.
   * @returns T
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 20 dynamic
   */
  get value(): T;
  /**
   * Set function that can set the new value.
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @crossplatform
   * @atomicservice
   * @since 20 dynamic
   */
  set value(newValue: T);
}

/**
 * The return result that defines whether the object data is observable.
 *
 * @interface ObservedResult
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @stagemodelonly
 * @crossplatform
 * @atomicservice
 * @since 23 dynamic
 */
export interface ObservedResult {
  /**
   * Whether the object data of class/Array/Map/Set/Date type is observable.
   * if true, the object data can be observed.
   * if false, the object data can not be not observed.
   *
   * @type { boolean }
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @stagemodelonly
   * @crossplatform
   * @atomicservice
   * @since 23 dynamic
   */
  isObserved: boolean;
  
  /**
   * Reasons why the object data of class/Array/Map/Set/Date type can not be not observed.
   * 1 The object data is not an observable object.
   * 2 The object data is observed data for the following reasons:
   * 2.1 The object data is decorated with @Observed or wrapped by makeV1Observed.
   * 2.2 The object data is decorated with V2 @ObservedV2 and @Trace.
   * 2.3 The object data is wrapped by V2's makeObserved.
   * 2.4 The object data is built-in type proxy data (Array/Map/Set/Date) decorated with @Trace.
   * 2.5 The V1 Observed object data is wrapped by enableV2Compatibility and used in @ComponentV2.
   * 2.6 The object data is decorated with @Observed or wrapped by makeV1Observed, but not used in UI.
   * 2.7 The object data is decorated with V2 @ObservedV2 and @Trace, but not used in UI.
   * 2.8 The object data is wrapped by V2's makeObserved, but not used in UI.
   * 2.9 The object data is built-in type proxy data (Array/Map/Set/Date) decorated with @Trace, but not used in UI.
   * 2.10 The V1 Observed object data is wrapped by enableV2Compatibility, but not used in @ComponentV2.
   *
   * @type { string }
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @stagemodelonly
   * @crossplatform
   * @atomicservice
   * @since 23 dynamic
   */
  reason: string;
  
  /**
   * The UI component information associated with the object data.
   * If the data object can not be observed, will return empty array.
   *
   * @type { Array<DecoratorInfo> }
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @stagemodelonly
   * @crossplatform
   * @atomicservice
   * @since 23 dynamic
   */
  decoratorInfo: Array<DecoratorInfo>;
}

/**
 * The UI component information associated with the object data.
 *
 * @interface DecoratorInfo
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @stagemodelonly
 * @crossplatform
 * @atomicservice
 * @since 23 dynamic
 */
export interface DecoratorInfo {
  /**
   * Decorator name of the object data.
   *
   * @type { string }
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @stagemodelonly
   * @crossplatform
   * @atomicservice
   * @since 23 dynamic
   */
  decoratorName: string;
  
  /**
   * State Variable name of the object data.
   *
   * @type { string }
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @stagemodelonly
   * @crossplatform
   * @atomicservice
   * @since 23 dynamic
   */
  stateVariableName: string;
  
  /**
   * The custom component name that the object data belongs to.
   * In the V1 scenario, return the custom component name, in the V2 @ObservedV2 scenario, return class name.
   *
   * @type { string }
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @stagemodelonly
   * @crossplatform
   * @atomicservice
   * @since 23 dynamic
   */
  owningComponentOrClassName: string;
  
  /**
   * The custom component id that the object data belongs to.
   * In the V1 scenario, return the custom component id, in the V2 @ObservedV2 scenario, return -1.
   *
   * @type { number }
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @stagemodelonly
   * @crossplatform
   * @atomicservice
   * @since 23 dynamic
   */
  owningComponentId: number;
  
  /**
   * Dependent component information including custom component and UI component (Text, Image)
   * for the object data.
   * For the V2 @Monitor or @Computed scenario, will return the id and decorated function name by @Monitor or @Computed.
   * For V2 scenario, if it is not used in the UI, nor on @Monitor or @Computed, return an empty array.
   * For V1 scenario, if it is not used in the UI, will return an empty array.
   *
   * @type { Array<ElementInfo> }
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @stagemodelonly
   * @crossplatform
   * @atomicservice
   * @since 23 dynamic
   */
  dependentInfo: Array<ElementInfo>;
}

/**
 * The custom component and UI component information.
 * For the V2 @Monitor or @Computed scenario, The id and decorated function name by @Monitor
 * or @Computed will be returned.
 *
 * @interface ElementInfo
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @stagemodelonly
 * @crossplatform
 * @atomicservice
 * @since 23 dynamic
 */
export interface ElementInfo {
  /**
   * Dependent custom component and UI component name.
   * For the V2 @Monitor or @Computed scenario, elementName refers to the name of the decorator and
   * the function name decorated with @Monitor or @Computed (eg: @Monitor onChange).
   *
   * @type { string }
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @stagemodelonly
   * @crossplatform
   * @atomicservice
   * @since 23 dynamic
   */
  elementName: string;

  /**
   * Dependent custom component and UI component id.
   * For the V2 @Monitor or @Computed scenario, elementId refers to the id of
   * the @Monitor or @Computed.
   *
   * @type { number }
   * @syscap SystemCapability.ArkUI.ArkUI.Full
   * @stagemodelonly
   * @crossplatform
   * @atomicservice
   * @since 23 dynamic
   */
  elementId: number;
}

/**
 * CustomComponent Lifecycle. It is used to monitor changes in the lifecycle of the custom component.
 *
 * @interface CustomComponentLifecycle
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @stagemodelonly
 * @crossplatform
 * @atomicservice
 * @since 23 dynamic
 */
export declare interface CustomComponentLifecycle {
    /**
     * getCurrentState method is to get the current lifecycle state.
     *
     * @returns { CustomComponentLifecycleState } - lifecycle state
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    getCurrentState(): CustomComponentLifecycleState;

    /**
     * Register a lifecycle listener. When the lifecycle state of a custom component changes, the corresponding
     * lifecycle callback will be triggered.
     *
     * @param { CustomComponentLifecycleObserver } observer - Custom component lifecycle observer.
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    addObserver(observer: CustomComponentLifecycleObserver): void;

    /**
     * Remove custom component lifecycle callbacks. Even if the custom component's lifecycle
     * state changes, the lifecycle callback will not be triggered.
     *
     * @param { CustomComponentLifecycleObserver } observer - Custom component lifecycle observer.
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    removeObserver(observer: CustomComponentLifecycleObserver): void;
}

/**
 * CustomComponent LifecycleObserver. When a user registers a custom component lifecycle callback, the
 * corresponding lifecycle callback will be triggered when the lifecycle changes.
 *
 * @interface CustomComponentLifecycleObserver
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @stagemodelonly
 * @crossplatform
 * @atomicservice
 * @since 23 dynamic
 */
export declare interface CustomComponentLifecycleObserver {
    /**
     * The aboutToAppear function is executed after a new instance of the custom component is created, before
     * its build() function is executed. Developers can modify state variables at this stage.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    aboutToAppear?(): void;

    /**
     * The onDidBuild function is executed after a new instance of the custom component
     * is built, after its build() function is executed. Developers can implement functions that do not
     * affect the actual UI, such as event data reporting at this stage.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    onDidBuild?(): void;

    /**
     * The aboutToDisappear function executes before a custom component is destroyed. It is not allowed to
     * change state variables within the `aboutToDisappear` function, especially since
     * modifying @Link variables may lead to unstable application behavior.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    aboutToDisappear?(): void;

    /**
     * The aboutToAttach function is executed when a custom component is attached to the main tree.
     * Developers can implement functions that do not affect the actual UI, such as event data reporting at this stage.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    aboutToAttach?(): void;

    /**
     * The aboutToDetach function executes when a custom component is detached from the main tree.
     * Developers can implement functions that do not affect the actual UI, such as initialization of non-state
     * variable data at this stage.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    aboutToDetach?(): void;

    /**
     * Invoked when a reusable custom component is re-added to the node tree
     * from the reuse cache to receive construction parameters of the component. When params is not undefined, it is the
     * callback for reusing the V1 component. when params is undefined, it is the callback for reusing the V2 component.
     *
     * @param { Record<string, Object | undefined |null> } [params] - Custom component init params.
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    aboutToReuse?(params?: Record<string, Object | undefined | null>): void;

    /**
     * Callback function invoked from the native side function 'CustomNodeBase::SetRecycleFunction'
     * when the component is about to be recycled.
     * It first calls the `aboutToRecycle` function in the application, and performs the necessary actions
     * defined in the application before recycling.
     * Then, it freezes the component to avoid performing UI updates when its in recycle pool
     * Finally recursively traverses all subcomponents, calling `aboutToRecycle` on each subcomponent
     * that is about to be recycled, preparing them for recycling as well.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    aboutToRecycle?(): void;
}

/**
 * Enum for Lifecycle State type
 *
 * @enum { number }
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @stagemodelonly
 * @crossplatform
 * @atomicservice
 * @since 23 dynamic
 */
export declare enum CustomComponentLifecycleState {
    /**
     * Lifecycle init state. Custom components are in this state when they are created.
     * The next state after the init state is the appear state,
     * which will trigger aboutToAppear.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    INIT = 0,

    /**
     * Lifecycle appeared state. Custom components are in this stage when they are about to be built.
     * The next state after the appeared state is the built state, which
     * will trigger onDidBuild.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    APPEARED = 1,
    
    /**
     * Lifecycle built state. The next state after the built state could be the recycled state,
     * or it could transfer to the disappeared state, or even transfer to the mounted state.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    BUILT = 2,
    
    /**
     * Lifecycle mounted state. Custom components are in this stage when they are attached
     * to the main tree or detached from the main tree.
     * The next state after the mounted state could be the built state, or it could
     * transfer to the disappeared state.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    MOUNTED = 3,
    
    /**
     * Lifecycle recycled state. Custom components are in a state of being recycled or reused.
     * The next state after the recycle state could be the
     * built state, or it could transfer to the disappeared state.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    RECYCLED = 4,
    
    /**
     * Lifecycle disappeared state. The disappeared state is the end state of a custom component's lifecycle.
     * The init, built, recycled, or mounted states could transfer to the disappeared state.
     *
     * @syscap SystemCapability.ArkUI.ArkUI.Full
     * @stagemodelonly
     * @crossplatform
     * @atomicservice
     * @since 23 dynamic
     */
    DISAPPEARED = 5
}

/**
 * Define ComponentInit PropertyDecorator.
 * When a custom component initialization is about to be completed, the function
 * decorated by the decorator will be executed.
 * Developers cannot modify state variables in this stage.
 *
 * @type { MethodDecorator }
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @stagemodelonly
 * @crossplatform
 * @atomicservice
 * @since 23 dynamic
 */
export declare const ComponentInit: MethodDecorator;

/**
 * Define ComponentAppear PropertyDecorator.
 * The function decorated by the decorator is executed after a new instance of the custom component is created, before
 * its build() function is executed. Developers can modify state variables at this stage.
 *
 * @type { MethodDecorator }
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @stagemodelonly
 * @crossplatform
 * @atomicservice
 * @since 23 dynamic
 */
export declare const ComponentAppear: MethodDecorator;

/**
 * Define ComponentBuilt PropertyDecorator.
 * The function decorated by the decorator is executed after a new instance of the custom component
 * is built, after its build() function is executed. Developers can implement functions that do not
 * affect the actual UI, such as event data reporting at this stage.
 *
 * @type { MethodDecorator }
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @stagemodelonly
 * @crossplatform
 * @atomicservice
 * @since 23 dynamic
 */
export declare const ComponentBuilt: MethodDecorator;

/**
 * Define ComponentAttach PropertyDecorator.
 * The function decorated by the decorator is executed when a custom component is attached to the main tree.
 * Developers can implement functions that do not affect the actual UI, such as event data reporting at this stage.
 *
 * @type { MethodDecorator }
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @stagemodelonly
 * @crossplatform
 * @atomicservice
 * @since 23 dynamic
 */
export declare const ComponentAttach: MethodDecorator;

/**
 * Define ComponentDetach PropertyDecorator.
 * The function decorated by the decorator is executed when a custom component is detached from the main tree.
 * Developers can implement functions that do not affect the actual UI, such as initialization of non-state
 * variable data at this stage.
 *
 * @type { MethodDecorator }
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @stagemodelonly
 * @crossplatform
 * @atomicservice
 * @since 23 dynamic
 */
export declare const ComponentDetach: MethodDecorator;

/**
 * Define ComponentReuse PropertyDecorator.
 * The function decorated by the decorator is invoked when a reusable custom component is re-added to the node tree
 * from the reuse cache to receive construction parameters of the component.
 *
 * @type { MethodDecorator }
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @stagemodelonly
 * @crossplatform
 * @atomicservice
 * @since 23 dynamic
 */
export declare const ComponentReuse: MethodDecorator;

/**
 * Define ComponentRecycle PropertyDecorator.
 * The function decorated by the decorator is invoked from the native side function 'CustomNodeBase::SetRecycleFunction'
 * when the component is about to be recycled.
 * It first calls the function in the application, and performs the necessary actions
 * defined in the application before recycling.
 * Then, it freezes the component to avoid performing UI updates when its in recycle pool
 * Finally recursively traverses all subcomponents, calling the function on each subcomponent
 * that is about to be recycled, preparing them for recycling as well.
 *
 * @type { MethodDecorator }
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @stagemodelonly
 * @crossplatform
 * @atomicservice
 * @since 23 dynamic
 */
export declare const ComponentRecycle: MethodDecorator;

/**
 * Define ComponentDisappear PropertyDecorator.
 * The function decorated by the decorator is invoked from the native side function 'CustomNodeBase::SetRecycleFunction'
 * when the component is about to be recycled.
 * It first calls the function in the application, and performs the necessary actions
 * defined in the application before recycling.
 * Then, it freezes the component to avoid performing UI updates when its in recycle pool
 * Finally recursively traverses all subcomponents, calling the function on each subcomponent
 * that is about to be recycled, preparing them for recycling as well.
 *
 * @type { MethodDecorator }
 * @syscap SystemCapability.ArkUI.ArkUI.Full
 * @stagemodelonly
 * @crossplatform
 * @atomicservice
 * @since 23 dynamic
 */
export declare const ComponentDisappear: MethodDecorator;