/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file Declares the APIs for privacy-preserving computation, including privacy target generation,
 *        privacy search, and search result retrieval.
 * @kit DataProtectionKit
 */

/**
 * The namespace of privacyComputation, providing privacy-preserving computation capabilities
 * such as privacy target generation, privacy search, and search result retrieval.
 *
 * @syscap SystemCapability.Security.Asset
 * @FaAndStageModel
 * @atomicservice
 * @since 26.1.0
 */
declare namespace privacyComputation {
  /**
   * Generates a privacy target for the given element. The privacy target is an encrypted representation
   * of the search element that can be used in a privacy-preserving search without revealing the original data.
   * This API uses a promise to return the result.
   *
   * @param { TargetElement } targetElement - The element to search for, including its raw data and optional hash
   *     algorithm.
   * @param { PrivacyProtocol } privacyProtocol - The privacy protocol configuration, including data set size and
   *     protocol type.
   * @returns { Promise<Uint8Array> } Promise used to return the encryption result.
   * @throws { BusinessError } 24000006 - Insufficient memory.
   * @throws { BusinessError } 24000018 - Parameter verification failed.
   * @syscap SystemCapability.Security.Asset
   * @FaAndStageModel
   * @atomicservice
   * @since 26.1.0
   */
  function genPrivacyTarget(targetElement: TargetElement, privacyProtocol: PrivacyProtocol): Promise<Uint8Array>;

  /**
   * Performs a privacy-preserving search. Searches the given dataset elements against the encrypted privacy target
   * without revealing the target or the dataset contents to the other party.  This API uses a promise to return the
   * result.
   *
   * @param { Uint8Array } privacyTarget - The encrypted privacy target generated by genPrivacyTarget.
   * @param { Element[] } elements - The dataset elements to search against.
   * @param { PrivacyProtocol } privacyProtocol - The privacy protocol configuration, including data set size and
   *     protocol type.
   * @returns { Promise<PrivacySearchResult> } Promise used to return PrivacySearchResult.
   * @throws { BusinessError } 24000006 - Insufficient memory.
   * @throws { BusinessError } 24000018 - Parameter verification failed.
   * @syscap SystemCapability.Security.Asset
   * @FaAndStageModel
   * @atomicservice
   * @since 26.1.0
   */
  function privacySearch(privacyTarget: Uint8Array, elements: Element[], privacyProtocol: PrivacyProtocol):
        Promise<PrivacySearchResult>;
  /**
   * Get the privacy search result and the final search outcome. Decrypts the search result ciphertexts
   * returned by privacySearch to obtain the final match result and optional attached value.  This API uses a promise
   * to return the result.
   *
   * @param { PrivacySearchResult } privacySearchResult - The result returned by privacySearch.
   * @param { PrivacyProtocol } privacyProtocol - The privacy protocol configuration, including data set size and
   *     protocol type.
   * @returns { Promise<SearchResult> } Promise used to return the searchResult.
   * @throws { BusinessError } 24000006 - Insufficient memory.
   * @throws { BusinessError } 24000018 - Parameter verification failed.
   * @syscap SystemCapability.Security.Asset
   * @FaAndStageModel
   * @atomicservice
   * @since 26.1.0
   */
  function getSearchResult(privacySearchResult: PrivacySearchResult, privacyProtocol: PrivacyProtocol):
        Promise<SearchResult>;
  /**
   * Defines the hash algorithms used for privacy-preserving computation.
   *
   * @syscap SystemCapability.Security.Asset
   * @FaAndStageModel
   * @atomicservice
   * @since 26.1.0
   */
  enum HashAlg {
    /**
     * The SHA256 hash algorithm.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    SHA256 = 0,
    /**
     * The SHA512 hash algorithm.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    SHA512 = 1
  }

  /**
   * Enumerates the data set sizes supported by the privacy protocol. The data set size defines
   * the number of comparisons that a single result ciphertext can contain. The total number of
   * result ciphertexts generated is determined by elements.size / dataSetSize. Choose an
   * appropriate data set size based on the number of elements in privacySearch and the acceptable
   * size of each result ciphertext.
   *
   * @syscap SystemCapability.Security.Asset
   * @FaAndStageModel
   * @atomicservice
   * @since 26.1.0
   */
  enum DataSetSize {
    /**
     * A single result ciphertext can contain 128 comparisons.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    SIZE_128 = 0,
    /**
     * A single result ciphertext can contain 256 comparisons.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    SIZE_256 = 1,
    /**
     * A single result ciphertext can contain 512 comparisons.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    SIZE_512 = 2
  }

  /**
   * Enumerates the privacy protocol types. The protocol type determines the privacy-preserving
   * computation method used for the search operation.
   *
   * @syscap SystemCapability.Security.Asset
   * @FaAndStageModel
   * @atomicservice
   * @since 26.1.0
   */
  enum ProtocolType {
    /**
     * Private Set Intersection (PSI) protocol. Used to check whether a target element exists
     * in the dataset without revealing the element or the dataset contents.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    PSI_PROTOCOL = 0,
    /**
     * Private Information Retrieval (PIR) protocol. Used to retrieve the value associated with
     * a matched key in the dataset without revealing the key or the retrieved value.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    PIR_PROTOCOL = 1
  }

  /**
   * Defines the privacy protocol configuration, including the data set size and protocol type
   * used for privacy-preserving computation.
   *
   * @syscap SystemCapability.Security.Asset
   * @FaAndStageModel
   * @atomicservice
   * @since 26.1.0
   */
  interface PrivacyProtocol {
    /**
     * The data set size for the privacy protocol. Determines the number of comparisons
     * that a single result ciphertext can contain. The total number of result ciphertexts
     * generated is determined by elements.size / dataSetSize. Choose an appropriate data set
     * size based on the number of elements in privacySearch and the acceptable size of each
     * result ciphertext.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    dataSetSize: DataSetSize;
    /**
     * The protocol type for the privacy computation. Determines the privacy-preserving
     * computation method (PSI or PIR).
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    protocolType: ProtocolType;
  }

  /**
   * Defines the target element for privacy computation, including the raw element data
   * and an optional hash algorithm.
   *
   * @syscap SystemCapability.Security.Asset
   * @FaAndStageModel
   * @atomicservice
   * @since 26.1.0
   */
  interface TargetElement {
    /**
     * The raw data of the target element to be searched for.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    elemData: Uint8Array;
    /**
     * The hash algorithm used for hashing the target element. If not specified, the element
     * data will be used with SHA256 default.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    hashAlg?: HashAlg;
  }

  /**
   * Defines a dataset element used in privacy search. Each element contains a key for matching,
   * an optional hash algorithm, and an optional value for PIR protocol retrieval.
   *
   * @syscap SystemCapability.Security.Asset
   * @FaAndStageModel
   * @atomicservice
   * @since 26.1.0
   */
  interface Element {
    /**
     * The key of the dataset element, used for matching against the privacy target.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    elemKey: Uint8Array;
    /**
     * The hash algorithm used for hashing the element key. If not specified, the element key
     * will be used with SHA256 default.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    hashAlg?: HashAlg;
    /**
     * The value associated with the element key. This field is used in PIR protocol to
     * retrieve the attached value when a match is found. If not specified, the element
     * only supports key matching without value retrieval.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    elemValue?: Uint8Array;
  }

  /**
   * Defines the result of a privacy search operation, containing the result ciphertexts
   * and optional value ciphertexts.
   *
   * @syscap SystemCapability.Security.Asset
   * @FaAndStageModel
   * @atomicservice
   * @since 26.1.0
   */
  interface PrivacySearchResult {
    /**
     * The array of result ciphertexts generated during the privacy search.
     * These ciphertexts encode the search result and need to be decrypted by getSearchResult.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    resultCipherText: Array<Uint8Array>;
    /**
     * The array of value ciphertexts generated during the privacy search when using PIR protocol.
     * These ciphertexts contain the encrypted values associated with the matched elements.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    valueCipherText?: Uint8Array[];
  }

  /**
   * Defines the final search result after decryption, indicating whether a match was found
   * and the optional attached value associated with the matched element.
   *
   * @syscap SystemCapability.Security.Asset
   * @FaAndStageModel
   * @atomicservice
   * @since 26.1.0
   */
  interface SearchResult {
    /**
     * Indicates whether the privacy target was found in the dataset. True means a match was found;
     * false means no match.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    matchedResult: boolean;
    /**
     * The attached value associated with the matched element. This field is available only when
     * using PIR protocol and a match is found; it is undefined otherwise.
     *
     * @syscap SystemCapability.Security.Asset
     * @FaAndStageModel
     * @atomicservice
     * @since 26.1.0
     */
    attachedValues?: Uint8Array[];
  }
}

export default privacyComputation;
